name: release
on: [push] # 仓库提交时触发
jobs:
  job1: # 发布任务
    runs-on: ubuntu-latest # 运行系统环境
    steps: # 步骤
      - name: build
        id: step_one
        run: |
          echo '构建安装'
          uname -a
          pwd 
          ls -al 
          ls ../ -l
          git clone https://github.com/liutingjieni/atop.git
          ls atop/ -l
          cd atop
          if !{atop -V} ;then 
            echo "assert" 
            exit
          fi
          #sudo make && sudo make install
          echo '安装完成'
  job2:
    runs-on: ubuntu-latest # 运行系统环境
    steps: # 步骤
      - name: build
        id: step_one
        run: |
          echo '测试'
          atop -V
          
