name: release
on: [push] # 仓库提交时触发
jobs:
  job1: # 发布任务
    runs-on: ubuntu-latest # 运行系统环境
    steps: # 步骤
      - name: build
        id: step_one
        run: |
          git clone https://github.com/liutingjieni/atop.git
          cd atop
          if atop -V ; then echo "assert: atop have installed "; exit;fi
          sudo make && sudo make install
          echo '安装完成'
          systemctl status atop.service 
          systemctl status atopacct.service
          systemctl status atop-rotate.timer
          systemctl cat atop.service
          systemctl cat atopacct.service
          systemctl cat atop-rotate.timer
      - name: subcmd_check
        id: step_two
        run: |
          if ! atop -V |grep -i Version; then echo "assert: atop -V error ";  atop -V; exit;fi
          if ! atop -h |grep -i Usage; then echo "assert: atop -h error "; atop -h; exit;fi
      - name: shadowfile_check
        id: step_three
        run: |
          if ! ls -A /run/pacct_shadow.d/|wc -l; then echo "assert: shadowfile_check error ";ls -A /run/pacct_shadow.d/; exit;fi
      - name: logfile_check
        id: step_four
        run: |
          ls -l /var/log/atop/
          if ! find  /var/log/atop/ -name "atop_*"|wc -l; then echo "assert: logfile_check error(/var/log/atop/) ";find  /var/log/atop/ -name \"atop_*\"； exit;fi
          
